In [23]:
import pandas as pd
import pyreadstat
import matplotlib.pyplot as plt
df = pd.read_spss("WV6_Data_sav_v20201117.sav")

In [9]:
df

,V1,V2,V2A,COW,C_COW_ALPHA,B_COUNTRY_ALPHA,V3,V4,V5,V6,...,I_DIVORLIB,CHOICE,WEIGHT3B,I_VOICE1,I_VOICE2,I_VOI2_00,VOICE,WEIGHT4B,Gender,Health
0,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,1.0,Very important,Very important,Very important,...,0.222222,0.074074,Complete,Very high,Medio,0.250,0.250,Complete,NaN,1.0
1,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,2.0,Very important,Rather important,Not very important,...,0.000000,0.000000,Complete,Low,Bajo,0.330,0.330,Complete,0.0,NaN
2,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,3.0,Very important,Not very important,Rather important,...,0.333333,0.111111,Complete,High,Bajo,0.165,0.165,Complete,0.0,NaN
3,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,4.0,Very important,Very important,Not very important,...,0.000000,0.000000,Complete,Very high,Bajo,0.000,0.000,Complete,0.0,NaN
4,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,5.0,Very important,Very important,Very important,...,0.222222,0.074074,Complete,Low,Bajo,0.330,0.330,Complete,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89560,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1496.0,Very important,Not very important,Rather important,...,0.000000,0.000000,Complete,Low,Alto,0.830,0.830,Complete,0.0,NaN
89561,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1497.0,Very important,Very important,Very important,...,0.000000,0.000000,Complete,Low,Medio,0.580,0.580,Complete,NaN,1.0
89562,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1498.0,Very important,Rather important,Very important,...,0.000000,0.000000,Complete,High,Alto,0.665,0.665,Complete,0.0,NaN
89563,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1499.0,Very important,Rather important,Rather important,...,0.444444,0.148148,Complete,Very high,Alto,0.500,0.500,Complete,0.0,NaN
89564,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1500.0,Very important,Rather important,Rather important,...,0.000000,0.000000,Complete,Very high,Alto,0.500,0.500,Complete,0.0,NaN

In [10]:
df.tail()

,V1,V2,V2A,COW,C_COW_ALPHA,B_COUNTRY_ALPHA,V3,V4,V5,V6,...,I_DIVORLIB,CHOICE,WEIGHT3B,I_VOICE1,I_VOICE2,I_VOI2_00,VOICE,WEIGHT4B,Gender,Health
89560,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1496.0,Very important,Not very important,Rather important,...,0.000000,0.000000,Complete,Low,Alto,0.830,0.830,Complete,0.0,NaN
89561,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1497.0,Very important,Very important,Very important,...,0.000000,0.000000,Complete,Low,Medio,0.580,0.580,Complete,NaN,1.0
89562,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1498.0,Very important,Rather important,Very important,...,0.000000,0.000000,Complete,High,Alto,0.665,0.665,Complete,0.0,NaN
89563,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1499.0,Very important,Rather important,Rather important,...,0.444444,0.148148,Complete,Very high,Alto,0.500,0.500,Complete,0.0,NaN
89564,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1500.0,Very important,Rather important,Rather important,...,0.000000,0.000000,Complete,Very high,Alto,0.500,0.500,Complete,0.0,NaN

In [25]:
df.loc[df['V10'] == 'Not at all happy', 'happiness'] = 4
df.loc[df['V10'] == 'Quite happy', 'happiness'] = 2

df.loc[df['V10'] == 'Not very happy', 'happiness'] = 3
df.loc[df['V10'] == 'Very happy', 'happiness'] = 1

In [26]:
# df.loc[df['happiness'] in (1.0, 2.0), 'happinessBin'] = 0
df['happiness'] = df.happiness.astype(str)
df.loc[df['happiness'] == "1.0", 'happinessBin'] = 0
df.loc[df['happiness'] == "2.0", 'happinessBin'] = 0
df.loc[df['happiness'] == "3.0", 'happinessBin'] = 1
df.loc[df['happiness'] == "4.0", 'happinessBin'] = 1
df['happinessBin']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
89560    1.0
89561    1.0
89562    1.0
89563    0.0
89564    0.0
Name: happinessBin, Length: 89565, dtype: float64

Which variables you think are related to happiness

In [41]:
#1.Sex
df['V240']

0          Male
1        Female
2        Female
3        Female
4        Female
          ...
89560    Female
89561      Male
89562    Female
89563    Female
89564    Female
Name: V240, Length: 89565, dtype: category
Categories (2, object): ['Female', 'Male']

In [42]:
#2.Information source: Internet
df['V223']

0         Weekly
1        Monthly
2          Daily
3        Monthly
4         Weekly
          ...
89560    Monthly
89561      Never
89562      Never
89563     Weekly
89564      Never
Name: V223, Length: 89565, dtype: category
Categories (5, object): ['Daily', 'Less than monthly', 'Monthly', 'Never', 'Weekly']

In [43]:
#3.Important in life: Family
df['V4']

0        Very important
1        Very important
2        Very important
3        Very important
4        Very important
              ...
89560    Very important
89561    Very important
89562    Very important
89563    Very important
89564    Very important
Name: V4, Length: 89565, dtype: category
Categories (4, object): ['Not at all important', 'Not very important', 'Rather important', 'Very important']

In [53]:
#4.Satisfaction with your life
df['V23']

0                              8
1                              5
2                              4
3                              8
4                              8
                  ...
89560    Completely dissatisfied
89561    Completely dissatisfied
89562                          4
89563    Completely dissatisfied
89564                          5
Name: V23, Length: 89565, dtype: category
Categories (10, object): ['2', '3', '4', '5', ..., '8', '9', 'Completely dissatisfied', 'Completely satisfied']

In [54]:
#State of health (subjective)
df['V11']

0        Very good
1             Good
2             Good
3        Very good
4             Fair
           ...
89560         Fair
89561    Very good
89562         Fair
89563         Good
89564         Good
Name: V11, Length: 89565, dtype: category
Categories (4, object): ['Fair', 'Good', 'Poor', 'Very good']

 properties of your data

In [44]:
#df.describe(include='all')
#1.Sex
df['V240'].describe()

count      89474
unique         2
top       Female
freq       46751
Name: V240, dtype: object

In [ ]:
#2.Information source: Internet
df['V223'].describe()

In [ ]:
#3.Important in life: Family
df['V4'].describe()

In [ ]:
#4.Satisfaction with your life
df['V23'].describe()

In [45]:
#State of health (subjective)
df['V11'].describe()

count     89239
unique        4
top        Good
freq      39632
Name: V11, dtype: object

 Recode everything that needs to be recoded

In [56]:
df.loc[df['V11'] == "Fair", 'Health'] = 0
df.loc[df['V11'] == "Good", 'Health'] = 1
df.loc[df['V11'] == "Poor", 'Health'] = 2
df.loc[df['V11'] == "Very good", 'Health'] = 3

In [29]:
df.loc[df['V240'] == "Female", 'Gender'] = 0
df.loc[df['V240'] == "Male", 'Gender'] = 1

In [4]:
df['V240']

0          Male
1        Female
2        Female
3        Female
4        Female
          ...
89560    Female
89561      Male
89562    Female
89563    Female
89564    Female
Name: V240, Length: 89565, dtype: category
Categories (2, object): ['Female', 'Male']

In [60]:
df

,V1,V2,V2A,COW,C_COW_ALPHA,B_COUNTRY_ALPHA,V3,V4,V5,V6,...,WEIGHT3B,I_VOICE1,I_VOICE2,I_VOI2_00,VOICE,WEIGHT4B,equal_or_lower_than_4?,happiness,happinessBin,Gender
0,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,1.0,Very important,Very important,Very important,...,Complete,Very high,Medio,0.250,0.250,Complete,3,2.0,0.0,3.0
1,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,2.0,Very important,Rather important,Not very important,...,Complete,Low,Bajo,0.330,0.330,Complete,3,2.0,0.0,1.0
2,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,3.0,Very important,Not very important,Rather important,...,Complete,High,Bajo,0.165,0.165,Complete,3,2.0,0.0,1.0
3,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,4.0,Very important,Very important,Not very important,...,Complete,Very high,Bajo,0.000,0.000,Complete,3,2.0,0.0,3.0
4,2010-2014,Algeria,Algeria,Algeria,ALG,DZA,5.0,Very important,Very important,Very important,...,Complete,Low,Bajo,0.330,0.330,Complete,NaN,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89560,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1496.0,Very important,Not very important,Rather important,...,Complete,Low,Alto,0.830,0.830,Complete,NaN,3.0,1.0,0.0
89561,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1497.0,Very important,Very important,Very important,...,Complete,Low,Medio,0.580,0.580,Complete,NaN,3.0,1.0,3.0
89562,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1498.0,Very important,Rather important,Very important,...,Complete,High,Alto,0.665,0.665,Complete,NaN,3.0,1.0,0.0
89563,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1499.0,Very important,Rather important,Rather important,...,Complete,Very high,Alto,0.500,0.500,Complete,3,2.0,0.0,1.0
89564,2010-2014,Zimbabwe,Zimbabwe,Zimbabwe,ZIM,ZWE,1500.0,Very important,Rather important,Rather important,...,Complete,Very high,Alto,0.500,0.500,Complete,3,2.0,0.0,1.0

In [ ]:
import matplotlib.pyplot as plt

df['happiness'] = df.happiness.astype(float)
df['index_column'] = df.index
df.plot(x ='happiness', y='index_column', kind = 'bar')

In [36]:
from scipy import stats
df['happiness'] = df.happiness.astype(float)
df['Gender'] = df.happiness.astype(float)
tval2, pval2 = stats.ttest_ind(df['happiness'], df['Gender'])  
print("t = " + str(tval2))  
print("p = " + str(pval2))

t = nan
p = nan

In [44]:
from sklearn.linear_model import LogisticRegression
from scipy.stats import chi2_contingency
import numpy as np

In [33]:
# Chi-square test of independence.
contigency= pd.crosstab(df['happiness'], df['Gender'])
c, p, dof, expected = chi2_contingency(contigency)
p

0.058451973290352795

In [50]:
#logistic regression
model = LogisticRegression(solver='liblinear', random_state=0)
x = df['happiness'].tolist()

x=np.array(x)
x=x.reshape(-1,1)
y=df['Gender'].tolist()

0.058451973290352795