In [1]:
import pandas as pd

In [2]:
#importing the dataset
df = pd.read_excel("Readmissions2021.xlsx")
df.head(10)

,patient_id,care_instance_no,gender,age,age_group,municipality_code,municipality_name,planned_unplanned,admission_code,admission_from,...,diagnosis1_code,diagnosis1_description,diagnosis2_code,diagnosis2_description,diagnosis3_code,diagnosis3_description,procedure1_code,procedure1_description,procedure2_code,procedure2_description
0,100004,17474276,0,112,85+,9909,Vägrar att uppge identitet,2,39,Från akutmottagning,...,S602,Kontusion på andra delar av handled och hand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100005,18348141,0,113,85+,9909,Vägrar att uppge identitet,2,39,Från akutmottagning,...,R519,Huvudvärk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100007,18337544,1,107,85+,1493,Mariestad,2,39,Från akutmottagning,...,S018,Sårskada på andra specificerade delar av huvudet,Z867C,Cerebral insult utan bestående men i den egna ...,I109,Essentiell hypertoni (högt blodtryck utan känd...,QAB00,Hudsutur i huvud-halsregion,NaN,NaN
3,100007,17706950,1,106,85+,1493,Mariestad,2,39,Från akutmottagning,...,G459,"Transitorisk cerebral ischemisk attack, ospeci...",I109,Essentiell hypertoni (högt blodtryck utan känd...,E039,"Hypotyreos, ospecificerad",NaN,NaN,NaN,NaN
4,100010,18016535,1,104,85+,1494,Lidköping,2,39,Från akutmottagning,...,R319,Ospecificerad hematuri (blod i urinen),I209,"Angina pectoris, ospecificerad",I209,"Angina pectoris, ospecificerad",NaN,NaN,NaN,NaN
5,100010,17466723,1,104,85+,1494,Lidköping,2,39,Från akutmottagning,...,I509,"Hjärtinsufficiens, ospecificerad",I252,Gammal hjärtinfarkt,NaN,NaN,DG015,Syrgasbehandling vid spontanandning och atmosf...,TKC20,Kateterisering av urinblåsa
6,100010,18016243,1,104,85+,1494,Lidköping,2,39,Från akutmottagning,...,J819,Lungödem,I209,"Angina pectoris, ospecificerad",I252,Gammal hjärtinfarkt,NaN,NaN,NaN,NaN
7,100012,18015083,1,103,85+,1471,Götene,2,39,Från akutmottagning,...,S5250,Fraktur på nedre delen av radius-sluten,I109,Essentiell hypertoni (högt blodtryck utan känd...,I209,"Angina pectoris, ospecificerad",TNC32,Modellerbar skena - Armbåge och underarm,ZXA05,Vänster sida
8,100019,18336590,1,103,85+,1471,Götene,2,39,Från akutmottagning,...,S010,Sårskada i hårbotten,I489,"Förmaksflimmer och förmaksfladder, ospecificerat",Z921,Långtidsanvändning (och pågående användning) a...,QAB00,Hudsutur i huvud-halsregion,NaN,NaN
9,100019,18340220,1,103,85+,1471,Götene,2,39,Från akutmottagning,...,S008,Ytlig skada på andra specificerade delar av hu...,I109,Essentiell hypertoni (högt blodtryck utan känd...,Z866A,TIA (transitoriska ischemiska attacker) i den ...,QAB00,Hudsutur i huvud-halsregion,AF074,Ortostatiskt prov (i)

In [4]:
#30 day rolling number of readmissions
df['readmission'] = df.set_index('admission_date').sort_index()\
                .groupby('patient_id', sort=False)['patient_id']\
                .rolling('30d', closed='both').count().tolist()
#Removing the intial admission
df.loc[:, 'readmission'] = df['readmission'].apply(lambda x: x - 1)


df[['patient_id','readmission']].head(10)

   patient_id  readmission
0      100004          0.0
1      100005          0.0
2      100007          0.0
3      100007          1.0
4      100010          0.0
5      100010          1.0
6      100010          2.0
7      100012          1.0
8      100019          1.0
9      100019          0.0

In [11]:
#Binary Readmission
df.loc[df['readmission'] > 0, 'readmission'] = 1

df.loc[df['readmission'] == 0, 'readmission'] = 0


df[['patient_id','readmission']].head(25)

    patient_id  readmission
0       100004          0.0
1       100005          0.0
2       100007          0.0
3       100007          1.0
4       100010          0.0
5       100010          1.0
6       100010          1.0
7       100012          1.0
8       100019          1.0
9       100019          0.0
10      100027          0.0
11      100031          0.0
12      100047          0.0
13      100048          0.0
14      100050          0.0
15      100051          0.0
16      100056          1.0
17      100062          0.0
18      100067          0.0
19      100067          0.0
20      100076          0.0
21      100081          0.0
22      100085          0.0
23      100085          0.0
24      100093          0.0

In [8]:
#The total readmissions
len(df[df['readmission'] == 1])

3623